### ISSUE TITLE
question about confidence intervals and estimate of population size

### ISSUE THREAD

**Issue by romunov** [mwpennell/capwire#1]
Hi,

I hope question about TIRM, I hope this is the correct venue.
Can you imagine a case where TIRM population size estimate would not be included in the confidence interval?

``` r
> bootstrapCapwire (fit = FTirm, bootstraps = 50)
$ml.pop.size
[1] 778

$conf.int
   2.5%   97.5% 
815.225 966.425 
```

Cheers,
Roman

**Comment by mwpennell** [comment]
Hi Roman,

Thanks for the comment. This is a tricky issue and I am not sure what to do about it. Since we don't have a nice way to compute confidence intervals for the estimator, we rely on parametric bootstrapping, meaning simulating new datasets under the maximum likelihood parameter estimates then re-estimating parameters on these simulated data sets. In general, this works fine. However, when there are very large deviations from its assumptions, the model may not be adequate to described the observed data and therefore the simulated data may look nothing like the observed. 

So yes, it is certainly possible that the ML estimate would be outside the confidence intervals. However, this is likely indicates that the model is not that great for this particular data set. I wasn't sure what to do when I wrote it: the older version of capwire simply changes the confidence interval so that it includes the ML estimate. However, I think that this is suboptimal as it hides potential issues about model adequacy. 

I know this is not a great answer but hopefully it is useful. Feel free to ping me back here with followups.

Matt

**Comment by romunov** [comment]
Hi,

that's exactly what we figured. Data may be from distribution X (say Chi^2) and the parametric bootstrap draws from distribution Y (say Normal). Parameters from X do not transfer well to Y (especially if you don't know what X actually is) and it goes downhill from there.
